env:
  global:
    - secure: daNW45GeBJ1OR2867A+PBGO0gEs8f83tJ5TYU8fbYyyiOfFmgCkADHo9Z6sp6RWWMo2Xt8X8Zh7pGlYcrjG1pGzxX8LtHA1JwCMZkiiV9AJamIykvA59lIATDFO4tuo+xnJH2fMC+Sbe6/dTR2jyxHeid80aqv/vmWKHQ1F+dTGL3+bArQROQHmkNuWCGoeN9APx1jtErqpP2+S2uY+gnDP+rxqFWQxI/1jocZFfUMMd/AmtQjukpSel0pgGc4pQbPbIbjIpwDYytFuto18E6Z1oJNjRxI1PSuNLN2mSHcSiDZ3F5H41zFxGgYjpMJBT7H9S2zULiqO1C/4Z7AX0WKt+WwRAQHvQ5sfs28EvMAwFOyIv9vhYM+mt/hoRZCGV5ZouFHfSeP+94MHo1NlT8UMGtFsFseixX2Wvw0aLWp49vxgjHHSnMiGPpoTSK/tzq2n0IAyOV+velUsDj0l2LpsldRibT9/n15lveOMb3gSc/gXwVEHSbFCDhE2fJjvE5bUeioXhUx4ORlbrieDpLBodbEkKI/8nS8AVataS3d2Ac9Y3zZWqSgBrJjVakpkoqRNt7jwtAwDDVhtUssEAekYRD6OIlplHp3xfxVXdeCMxs4JEptpMpoPqCIAzJoUCWZioJbxPAaclKtcii2GPaPz8wC4byophhGh+JmmVxpg=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/whitelist
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
