env:
  global:
    - secure: BqwPFEWJCnArebwvg7VyVBShi8K6SksA/q64Lp/UH5Y0d4nbdLURwACtX5dclycKp/r8SFhfhiJt3NFzNLuWScB/FhhikQwfmvsVSidlBVorIoZ0IgeVjpprAKhRWBFR3ooNTaXrj3TSlFZtpzMd1rCPaYs+FikavN8B9aPT/3fUG2Xbp6i+Ty98/8L5Ladij0D2NeOPtVWp5w3oEoMVHsLK13mIeMSYooPsf/1yfZIEIwdU8GmDdIKF6r88MwGI9fiWhoN2sQlQMKwilrKQm+CRHDpKTaAUnpxkEA/5hCBEp2fKHtrCHp5dIvDI3TIp3hl4tZwg32jmHMyte1R88i18nHZt5hfx86+SwmBqfB0bPIIcFcza8XION4i0/N12Wljc05uv9OAaPZku4BujOrPmCa3T2apdXCAyLqQO/fbEgfm5tcq52HzkoeXgZBia9r59AOSuIIK0MN93fanm65BSfCaN0OM8M5QdzlUlTtTQ3Qo971FidS8877JCBLVpMy9QhMmnmgG8c7nMHo64tT7cUpFbNTpGMdnOL7K3qMMX3cHvaQHGPE6JsOmAhVmBkt4pfSXP/jGAxLKetEPHcXhhsC+RXRbCvOphTeP/hYl2ndEFHG/9AqEgT4FkmNyzwMMKpValfvkpAEJLClr9gCjcCGMvHB5vSF8+e0rkye0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/whitelist
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
