env:
  global:
    - secure: k7MoxKoMU6yTuP10KaJ5sVxZ47+vq0JwCcbwAp8AWVN1nQcDT8zow3r149L40fU/hewNuifh3AUulz3f9cL+SaO7cL7olAOcVXbYRFDgJ+4W11KqdJ19hi+KnPi+JV72veljqfGYj0IgEbXPBlhyB31C0hsro+i4dfbYHkUBhTEEUIy4gxZOb9yLrgVlQ9uLQBToZ/UykVQY2YW6T6cN0OeDLu2auyA5YVMbekS4fSc+ipY9qUrZ67SWlA1Dpvfm5RdlIMR52zSCbgSOVxpQh8NS4cTtVZDZ0LMwlU6EmKE+wSdxGqRHdqCm340lCKl5NHbTnoyBTMlWTDl7x2GjAG4r3FqZvPNEYBgVRyDeacZ6XL06kiNCdcWGfToaI5nxABzal5n0k2zG6RuWyDyOPscTegm+T67SL09rkv+jnP4CLE1DnD3CieMBx5+KoGRDbDh31pr1ruyp64i8ay4THhxvzVlYXpXhtzL5OLBsOqsuTgim+vygSfi/8eUp6S0/kTF8XiW1QaAPR0iR4nPsNPPMJWn2XZWMXKtKb6jclh/ygPyD/G6TwQWgi9tDuLyE3kyVf69BoFoKb2iVjW1SWIyc7C3I7m28PuvNmtu4i9/BZ252Vu7O9WAJeAKvPvjjbefK5AEVi+0k5WCN9XqzwzU+5JaD5szH4LsPSTcjq18=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/whitelist
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
