env:
  global:
    - secure: JNxNyUKTRoU4t9Cl9SfESK086TfjRaMSHRGfZsXD/Xg2frRPxmJxkeI1Qtl9cJTcXrvP9G9oBm4nycamhDEiI5nHGR27U8/bN7+3Is8CRWB7/nI/B5e5W8WeveJ3nnVxJ16EJIIRm+q3bDhqbY/fEXbzqnTFkTTS073NExfG+cUSNoDq7I5mTBQNbMTYJ0GeJkNosuqHgMYxamSavN1lJ50u9Qy0x6QCXhaffoO3r2fqtt7Q7g2oTRQP5aDUlXahTFrTw15cPsGqbx04DqmwSncsH+WWsWJ1GWYIa2ZZqLpmDe5gIIv6XI3LMlx/CVxCbqqUz5AXikkAJ8QUVe16WyjP/MrzirgicsrYj4zOSQSjc8EbKF5MBhgHLKkE6uROAbqc7Mh/qms8+oAMPFNqgrM2P8LGQamFe6a/C0WlBRnDku/kZE4cIdH/bmupKWxjKMvGf1BmTCi3uXczEZcCc17no8ExJk8I+udCHWSJVbg3f5ylvPIG41b6G1uMzhRYXtmQotxd0WPSjusDVIXBGfJXtiSMNf/C9wmmEOyAA2GB5kOEXvHTtPS09JuJkGvOmCy4ATLqfR2uoXy6quAyNG2R2R0Uabpybb05wg3Chy/zyyYi5BmmSRzH2GIHKmoPMdFhKasEG0qnr5u8ZsBMxCC12ql8phMedpTYqCQwe+U=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/whitelist
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
