env:
  global:
    - secure: hOz6VIUZZwFZPGS7u+FEpWjsWRlmTZb2lwU5zRjHY0xXV7ZKWKVWLtC8AIVBBlsZKg3gZxKoXsOWRynqH1DB05W03rKV/ECi/wP0byu3uBBpy13zJORLPlwVPjVUDQEHW5J4AXCj3Mepb+cWCPUBSW3YSHZr6nAgWrz81RFmxY58ihsy/s6JNeMnydTpLyBWNUgXeLRQ9vt5jdU5VHdWgWeXpHcI3ausLTIT9HbyWdvXccrYmaeEvy5Zx5zf6QIvWG8DuD5hhyASc1+VPtx0omzVTeEw9USq3MsjUN0ZuHsn7dq9H7z0KfjrjmxIV3LToq4mjWdzNSbK+Y2OAj87Hqqhsvlrgty8eW9h/Pa8IvdDQaZYq/T4bKO9xRwpabIhYUuUbkp3vUQVaM1D5mcK/+zsp8wEBDPgr4f57zSGffJE9tgjcaUhXVbblywuSgoKXdYfAE4Vnlo1TKd3xS9GOVfWWNX9fkueXaiuw8F2v6SJT4PpQ1aBxEvu0Bv6UuraDWPqxHTkAfcjZUUb53qKz2jUZ10pMzXk+4ugrpjU2u4Kgp8mPNlTi0F10K6iIYdUNASPoov2dajwtBhH/C6lGghYfNXDqMQj0nRmYVcmAscj99PAO7RdtirQe1ltU+mPDkgQG0qM7Kdolgsw4i4ws1Pq5H1WXqjYWsFJdLrdM7s=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/whitelist
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
