env:
  global:
    - secure: eRWLY/ysE/EmyNsnT9UQ56GfM6uFtn8pvxwZJYlqiCE1SE6gpI6X2rEO2AVfEgSS4+0WX4/AJhuSCl5nCVgh3leey0VRvcxWSj6FLB20NDFmzgBs852d0hOyqFgzjHHJ9AGZm8o0oynfji7Pq2kb44nY/a/oa9yD40XXu4eLqMurpKEAb7PHZ4iUeCIqzdB0/9qjWlNYXZ2v2HupaYWQt21aPU7PuXKuDKfEbig12OhM25y79uWVMinT8LvGP4nX9Mxr9PzTRgHttiqjoy42xZS6lprZGMvvLr7y74qJiRSWXnJwDkPjq6oJevCSGa/Fp813xtnkRjiOm+J8fuCGuJJ7AMb2drWq8VyJOqrsZrz4anC0HVBqRTkORFvZHU5ncRIGJcwuVR4ndn+M9GYiC8cuMm8q4Z9IxcrYqs85/lHIm3zsf9RgvMcxbU0q9LHB53tB+6vvGody2cqju6JcdtgXEFcSV779rW4VjK9Tx58uMBLtz2bq+cJTT+61XWvmW9yIIrGZTaxZO2/QFsDRu5uyOzkrTPtuQXzLTpzleQGaRIjKftkfUrDaddtKUR+Gl2dwalwRcu7TwpE1xgMM54q8zec3yqh9cwISeuX61XzaH05mxGQrHuZE0NWwDP+LcGM3HkXmKGQSiUMvNMp0qvq25DBg1o3xcMwhDvDxUDo=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/whitelist
    - GIT_BRANCH: master
    - UPDATE_LOCATION: https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/repository-structure/master/update.py
    - ADMINISTATION_LOCATION: https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/repository-structure/master/administration.py

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests
  - pip3 install ultimate_hosts_blacklist_the_whitelist
  - if [[ ! -f .admin ]]; then wget "${UPDATE_LOCATION}" -o /dev/null -O update.py && chmod +x update.py; else echo "No need to download/update update.py."; fi
  - if [[ ! -f .admin ]]; then wget "${ADMINISTATION_LOCATION}" -o /dev/null -O administration.py && chmod +x administration.py; else echo "No need to download/update administration.py."; fi

script:
  - python3 ./update.py

notifications:
  on_success: change
  on_failure: always
