env:
  global:
    - secure: DaEBxbeTQcAZ5eUVEPHzRlaDOlZzQ7P01ZmzaPvf0MEFa+QIyQbbFHqI5hreBw6ZLzwYhS962igVmHqC3QjGBUW3SL5/bzEoiHFm+Hf0NA3IMw4LD74OcHWZI2euNtkfbBX1qEVNFU83pB97SHjvBnIaXPuyzsBoCfymoPDMx8kIC2K5rl1nQL8b08wZ5wDdUSgCmC8/+e93+EaYxJV/iKQqcDERUFVV1vs33NFm9wZQVxSgQtMsMi1zI1bngYepAMxYX5yuLyJadrN3sgrYeKICT/gAXVCKJpZ6GegKzRU4DoBvcP0gfMyrVEYAgxjSxRojbzG+T2/PiPDM81M+QRuwfik/v6WIGFQ/mJAKY43r1Idiw8VSlvYibjdPDqnc5dnZY41nmSDIWPh+U0h+1pBDfSgBgapM9qVQTLwwL6XvrR9ZaDcHtHqn3qBYx7JEXBioYrDmD9GIK6aKG7sMLW4RrBYXKe8ObU7MwpMLlbVe6E5hFkvCkpXRGHeBDondSrv1UwIO52SL9GkqWv3/qcbdEC7aQKOQI8xbbq1dfFZA82uBMa7KDcbWV1F+Xq6Dvap4W82QmQwObU+NnCqceTdO5wa60LnwIibCZrqEPwqJJw6vFdMN/FnNU/XvA9+/5tALQnlgCUb3LjYZDEoOom3NmCtEbpU4d0cFNXTYNEw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/whitelist
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
